### ISSUE TITLE
Schematic issues

### ISSUE THREAD

**Issue by micbeldyga** [sinara-hw/DIOT-Template#3] opened 2024-10-05 15:02 UTC
CPCIS_Connectors sheet:
- two different net names for SERVMOD signal: SERVMOD and SERVMOD_3V3.
![image](https://github.com/user-attachments/assets/da9d614b-f04d-452c-bfc8-39f3d7864fc9)
![image](https://github.com/user-attachments/assets/c3148d36-17ff-44be-a660-f0029ef48606)

- Unconnected GND pin on IC1
![image](https://github.com/user-attachments/assets/de824bb8-91a9-4fc1-8e41-b073d3e3d1cc)

EEM_Connectors sheet:
- EEM0 pairs 0-4 only routed to BP connector, no connections to the rest of the circuit
![image](https://github.com/user-attachments/assets/a267c896-0fbe-436c-b4e2-7b15d124f51b)

**Comment by micbeldyga** [comment] 2024-10-13 02:28
I2C_SDA and I2C_SCL nets don't connect anywhere
![image](https://github.com/user-attachments/assets/7422f784-f95c-4190-8dae-dce84c1ea603)
![image](https://github.com/user-attachments/assets/c4f75154-abf3-4800-b7db-5dfd40e0c3ad)
![image](https://github.com/user-attachments/assets/dd334aab-c57f-43f6-82ed-30b1a8a9db1a)

**Comment by micbeldyga** [comment] 2024-10-13 02:29
@gkasprow

**Comment by gkasprow** [comment] 2024-10-18 09:52
IC1 is duplicate of IC40

**Comment by gkasprow** [comment] 2024-10-18 10:00
fied

**Closed by gkasprow** 2024-10-18 10:00 UTC
